#!/bin/bash
export POD_CIDR="10.95.0.0/16"

export REGISTRY_MIRROR_URL=registry.nutanixdemo.com/nkpairgap              # Required on Nutanix HPOC or internet connected deployments to avoid docker rate limiting
#export REGISTRY_MIRROR_USERNAME='harbor user'                 # Required on Nutanix HPOC or internet connected deployments to avoid docker rate limiting
#export REGISTRY_MIRROR_PASSWORD='harbor password'                 # Required on Nutanix HPOC or internet connected deployments to avoid docker rate limiting
#export REGISTRY_MIRROR_CA_CERT_FILE=./registry-ca_cert.pem


#Flow-CNI parameters
export FLOWREGISTRY="harbor-fqdn"
export FLOW_CHART_VERSION="1.1.0-940"
export FLOW_CNS_CILIUM_TAG=169
export FLOW_K8S_CNI_TAG=940
export FLOW_OVN_KUBERNETES_TAG=230

export AIRGAP_REGISTRY_MIRROR_URL=${REGISTRY_MIRROR_URL}              # Required on Nutanix HPOC or internet connected deployments to avoid docker rate limiting
export AIRGAP_REGISTRY_MIRROR_USERNAME='harbor user'                 # Required on Nutanix HPOC or internet connected deployments to avoid docker rate limiting
export AIRGAP_REGISTRY_MIRROR_PASSWORD='harbor password'                 # Required on Nutanix HPOC or internet connected deployments to avoid docker rate limiting

export BASEOSIMAGEUSER=ubuntu

# Optional Proxy settings for image buiding

#export HTTP_PROXY=http://proxy:8080
#export HTTPS_PROXY=http://proxy:8080
#export NO_PROXY=localhost,127.0.0.1

# Optional Proxy settings for cluster

#export CLUSTER_HTTP_PROXY=http://proxy:8080
#export CLUSTER_HTTPS_PROXY=http://proxy:8080
#export CLUSTER_NO_PROXY=localhost,127.0.0.1

# export NIB_HTTP_PROXY=true