apiVersion: v1
kind: Namespace
metadata:
  name: testegress
---
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressip-netshoot
spec:
  egressIPs:
    - 10.38.143.35
  namespaceSelector:
    matchLabels: 
      kubernetes.io/metadata.name: default
  podSelector:
    matchLabels:
      app: netshoot-egress-ip
# This is an egressip specific to app netshoot-egress-ip in namespace default. 
---
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressip-namespace
spec:
  egressIPs:
    - 10.38.143.36
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: testegress
# This is an egressip for all pods in namespace testegress.      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-egress-ip
  namespace: default
spec:
  selector:
    matchLabels:
      app: netshoot-egress-ip
  template:
    metadata:
      labels:
        app: netshoot-egress-ip
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 3600; done"]
# This is a deployment of netshoot pods in namespace default that will use the specific egressip 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-egress-namespace
  namespace: testegress
spec:
  selector:
    matchLabels:
      app: netshoot-egress-namespace
  template:
    metadata:
      labels:
        app: netshoot-egress-namespace
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 3600; done"]
# This is a deployment of netshoot pods in namespace testegress that will use the egressip for the entire namespace.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot-no-egress-ip
  namespace: default
spec:
  selector:
    matchLabels:
      app: netshoot-no-egress-ip
  template:
    metadata:
      labels:
        app: netshoot-no-egress-ip
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        command: ["/bin/bash"]
        args: ["-c", "while true; do sleep 3600; done"]
# This is a deployment of netshoot pods in the default namespace that will not use any egressip.